# Generated by Django 3.1.2 on 2020-10-24 13:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='No image', upload_to='project/')),
                ('title', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('link', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=30)),
                ('posted', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usability', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10, message='Range acceptable is 0-10'), django.core.validators.MinValueValidator(0)])),
                ('design', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10, message='Range acceptable is 0-10'), django.core.validators.MinValueValidator(0)])),
                ('content', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10, message='Range acceptable is 0-10'), django.core.validators.MinValueValidator(0)])),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.png', upload_to='profile/')),
                ('bio', models.TextField(blank=True)),
                ('contact', models.CharField(blank=True, max_length=30)),
                ('location', models.CharField(blank=True, max_length=50)),
                ('company', models.CharField(blank=True, max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
